#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# AUTOSTART #
#-----------#
xwallpaper --focus $HOME/.wal/night-forest.jpg &
~/.config/herbstluftwm/launch.sh &

# REMOVE ALL EXISTING KEYBINDINGS #
#---------------------------------#
hc keyunbind --all

# KEYBINDINGS #
#-------------#
Mod=Mod4   # Use the super key as the main modifier

# System controls #
#-----------------#
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn "${TERMINAL:-kitty}" # 

# multimedia #
#------------#
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume 0 +5%
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume 0 -5%
hc keybind XF86AudioMute spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
hc keybind XF86AudioPlay spawn playerctl play-pause
hc keybind XF86AudioNext spawn playerctl next
hc keybind XF86AudioPrev spawn playerctl previous
hc keybind $Mod-Control-s spawn playerctl stop

# run launchers #
#---------------#
hc keybind $Mod-Shift-Return spawn rofi -show run -show-icons

# My Keybinds #
#----------#

hc keybind $Mod-Alt-f spawn pcmanfm
hc keybind $Mod-Alt-e spawn microsoft-edge-stable
hc keybind $Mod-Alt-g spawn google-chrome-stable
hc keybind $Mod-Alt-t spawn telegram-desktop
hc keybind $Mod-Alt-m spawn thunderbird
hc keybind $Mod-Alt-d spawn discord
hc keybind Print spawn scrot -d 3 ~/.screenshots/%Y-%m-%d-%T-screenshot.png

# scratchpads #
#-------------#
hc keybind Control-1 spawn tdrop -am -w 1000 -h 600 -x 450 -y 200 -n 0 kitty
hc keybind Control-2 spawn tdrop -am -w 1000 -h 600 -x 450 -y 200 -n 1 kitty -e ncmpcpp
hc keybind Control-3 spawn tdrop -am -w 1000 -h 450 -x 450 -y 200 -n 2 kitty -e ranger
hc keybind Control-4 spawn tdrop -am -n 3 bitwarden-desktop
# hc keybind Control-4 spawn tdrop -am -w 1000 -h 600 -x 230 -y 100 -n 3 bitwarden-desktop
hc keybind Control-5 spawn tdrop -am -w 1200 -h 800 -x 380 -y 150 -n 4 kitty

# focusing client #
#-----------------#s
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients in tiling and floating mode #
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames #
#------------------#
hc keybind $Mod-u       split   bottom  0.6
hc keybind $Mod-o       split   right   0.6

# let the current frame explode into subframes #
#----------------------------------------------#
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients #
#--------------------------------------#
resizestep=0.02
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

herbstclient set_monitors 1920x1080+0+0

# tags #
#------#
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    hc set_layout horizontal
    hc set default_frame_layout 1
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting #
#-----------#
hc keybind $Mod-r remove
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# focus #
#-------#
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# MOUSE #
#-------#
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc set focus_follows_mouse 1

# THEME #
#-------#
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#ffffff'
hc attr theme.normal.color '#007687'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.active.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.color '#b8b8b8'
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
#hc attr theme.active.inner_color '#3E4A00'
#hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings false
hc set smart_frame_surroundings false
hc set mouse_recenter_gap 0

# RULES #
#-------#
hc unrule -F

hc rule class="Pcmanfm" tag=2 switchtag=on
hc rule class="Thunar" tag=2 switchtag=on
hc rule class="Microsoft-edge" tag=3 switchtag=on
hc rule class="Google-chrome" tag=4 switchtag=on
hc rule class="TelegramDesktop" tag=5 switchtag=on
hc rule class="thunderbird" tag=6 switchtag=on
hc rule class="discord" tag=7 switchtag=on
hc rule class="Transmission-gtk" tag=8 switchtag=on

hc rule focus=on # normally focus new clients
hc rule floatplacement=center
#hc rule float_geometry=250x100
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on floatplacement=center
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

hc rule title~'Bitwarden' floating=on floatplacement=center floating_geometry=1000x800
hc rule title~'Gpick' floating=on floatplacement=center floating_geometry=1000x800

# UNLOCK #
#--------#
hc unlock


# FIND THE PANEL #
#----------------#
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
hc split vertical 0.6; hc remove

