#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale ~/.wal/tardis.jpg &
nm-applet &
udiskie -ta &
mpd &
picom &
polkit-dumb-agent &
blueman-applet &
dunst &
numlockx &
xset dpms 0 0 0 && xset s off && xset s noblank &
~/.git/dotfiles/.config/polybar/launch.sh &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Thunar desktop='^2' focus=on 
bspc rule -a Microsoft-edge desktop='^3' focus=on 
bspc rule -a Google-chrome desktop='^4' focus=on 
bspc rule -a TelegramDesktop desktop='^5' focus=on 
bspc rule -a thunderbird desktop='^6' focus=on 
bspc rule -a Discord desktop='^7' focus=on 

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
